import type { Metadata } from 'next'
import { getProduct } from '@/lib/productStore'

const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || 'https://eonni.com.ua').trim().replace(/\/$/, '')

type Props = {
  params: { id: string }
  children: React.ReactNode
}

function decodeId(id: string): string {
  // Cyrillic IDs arrive percent-encoded in dynamic route params on some Next.js
  // builds; decode defensively so DB lookups don't silently miss.
  try {
    return decodeURIComponent(id)
  } catch {
    return id
  }
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  try {
    const product = await getProduct(decodeId(params.id))
    if (!product) {
      return {
        title: 'Товар не знайдено',
        robots: { index: false, follow: false },
      }
    }

    const title = product.name
    const description =
      product.short_description ||
      product.long_description?.slice(0, 200) ||
      `${product.name} — оригінальна корейська косметика в Eonni. Швидка доставка по Україні.`

    const canonical = `${SITE_URL}/product/${product.id}`

    return {
      title,
      description,
      alternates: { canonical },
      openGraph: {
        type: 'website',
        url: canonical,
        title,
        description,
        locale: 'uk_UA',
        siteName: 'Eonni',
        // OG image is auto-generated by ./opengraph-image.tsx using the product photo
      },
      twitter: {
        card: 'summary_large_image',
        title,
        description,
      },
    }
  } catch (err) {
    console.error('[product/generateMetadata] error:', err)
    return { title: 'Товар' }
  }
}

export default async function ProductLayout({ params, children }: Props) {
  let productJsonLd: Record<string, unknown> | null = null
  let breadcrumbJsonLd: Record<string, unknown> | null = null
  let faqJsonLd: Record<string, unknown> | null = null

  try {
    const product = await getProduct(decodeId(params.id))
    if (product) {
      const image = product.image_url || product.image_path || `${SITE_URL}/logo.svg`
      const productUrl = `${SITE_URL}/product/${product.id}`

      productJsonLd = {
        '@context': 'https://schema.org',
        '@type': 'Product',
        name: product.name,
        description: product.short_description || product.long_description || product.name,
        image: [image],
        brand: product.brand
          ? { '@type': 'Brand', name: product.brand }
          : undefined,
        category: product.category || undefined,
        sku: product.sku || product.id,
        offers: product.sale_price
          ? {
              '@type': 'Offer',
              url: productUrl,
              priceCurrency: 'UAH',
              price: product.sale_price,
              availability:
                product.stock_quantity && product.stock_quantity > 0
                  ? 'https://schema.org/InStock'
                  : 'https://schema.org/PreOrder',
              itemCondition: 'https://schema.org/NewCondition',
              hasMerchantReturnPolicy: {
                '@type': 'MerchantReturnPolicy',
                applicableCountry: 'UA',
                returnPolicyCategory: 'https://schema.org/MerchantReturnFiniteReturnWindow',
                merchantReturnDays: 14,
                returnMethod: 'https://schema.org/ReturnByMail',
                returnFees: 'https://schema.org/FreeReturn',
              },
              shippingDetails: {
                '@type': 'OfferShippingDetails',
                shippingRate: {
                  '@type': 'MonetaryAmount',
                  value: '70',
                  currency: 'UAH',
                },
                shippingDestination: {
                  '@type': 'DefinedRegion',
                  addressCountry: 'UA',
                },
                deliveryTime: {
                  '@type': 'ShippingDeliveryTime',
                  handlingTime: { '@type': 'QuantitativeValue', minValue: 0, maxValue: 1, unitCode: 'DAY' },
                  transitTime: { '@type': 'QuantitativeValue', minValue: 1, maxValue: 3, unitCode: 'DAY' },
                },
              },
            }
          : undefined,
        aggregateRating:
          product.rating && product.review_count
            ? {
                '@type': 'AggregateRating',
                ratingValue: product.rating,
                reviewCount: product.review_count,
              }
            : {
                '@type': 'AggregateRating',
                ratingValue: 5,
                reviewCount: 1,
              },
      }

      // Breadcrumbs: Home › Catalog › Category › Product
      const crumbs: Array<{ name: string; url: string }> = [
        { name: 'Головна', url: SITE_URL },
        { name: 'Каталог', url: `${SITE_URL}/catalog` },
      ]
      if (product.category) {
        crumbs.push({
          name: product.category,
          url: `${SITE_URL}/catalog?category=${encodeURIComponent(product.category)}`,
        })
      }
      crumbs.push({ name: product.name, url: productUrl })

      breadcrumbJsonLd = {
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        itemListElement: crumbs.map((c, i) => ({
          '@type': 'ListItem',
          position: i + 1,
          name: c.name,
          item: c.url,
        })),
      }

      // FAQ schema — mirrors the FAQ section visible on every product page.
      faqJsonLd = {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        mainEntity: [
          {
            '@type': 'Question',
            name: 'Чи підходить цей засіб для чутливої шкіри?',
            acceptedAnswer: {
              '@type': 'Answer',
              text: 'Так, формула розроблена для чутливої та реактивної шкіри. Перед першим застосуванням рекомендуємо протестувати засіб на невеликій ділянці шкіри.',
            },
          },
          {
            '@type': 'Question',
            name: 'Як часто використовувати засіб?',
            acceptedAnswer: {
              '@type': 'Answer',
              text: 'Рекомендована частота — щодня, відповідно до інструкції на упаковці та етапу вашого догляду.',
            },
          },
          {
            '@type': 'Question',
            name: 'Можна використовувати ранком та ввечері?',
            acceptedAnswer: {
              '@type': 'Answer',
              text: 'Так, засіб підходить для ранкового та вечірнього догляду. У ранковій рутині завершіть догляд SPF.',
            },
          },
          {
            '@type': 'Question',
            name: 'Через скільки часу буде помітний результат?',
            acceptedAnswer: {
              '@type': 'Answer',
              text: 'Перші зміни помітні через 2-4 тижні регулярного використання. Стійкий результат — 6-8 тижнів.',
            },
          },
        ],
      }
    }
  } catch (err) {
    console.error('[product/jsonld] error:', err)
  }

  return (
    <>
      {productJsonLd && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(productJsonLd) }}
        />
      )}
      {breadcrumbJsonLd && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
        />
      )}
      {faqJsonLd && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
        />
      )}
      {children}
    </>
  )
}
