import type { Metadata } from 'next'
import '@/styles/globals.css'
import { CartProvider } from '@/contexts/CartContext'
import { WishlistProvider } from '@/contexts/WishlistContext'
import Header from '@/components/layout/Header'
import SupportFAB from '@/components/SupportFAB'
import LenisProvider from '@/components/providers/LenisProvider'
import MicrosoftClarity from '@/components/analytics/MicrosoftClarity'

const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || 'https://eonni.com.ua').trim().replace(/\/$/, '')
const SITE_NAME = 'eonni — корейська косметика в Києві'
const SITE_DESCRIPTION =
  'Інтернет-магазин корейської косметики eonni у Києві. Оригінальна K-beauty: догляд за обличчям, тілом, волоссям, БАДи та косметичні девайси від Medicube, Mediheal, Torriden, UNOVE, VT Cosmetics. Доставка по Києву та всій Україні.'

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_NAME,
    template: '%s | eonni',
  },
  description: SITE_DESCRIPTION,
  applicationName: 'eonni',
  generator: 'Next.js',
  keywords: [
    'корейська косметика',
    'корейська косметика київ',
    'корейська косметика україна',
    'купити корейську косметику',
    'купити корейську косметику київ',
    'k-beauty',
    'k-beauty київ',
    'k-beauty Україна',
    'магазин корейської косметики',
    'магазин корейської косметики київ',
    'корейські засоби київ',
    'корейська косметика Оболонь',
    'eonni',
    'медікуб',
    'medicube',
    'mediheal',
    'torriden',
    'unove',
    'vt cosmetics',
    'лактофіт',
    'lactofit',
    'корейські БАДи',
    'корейські маски',
    'догляд за шкірою',
    'тонер корейський',
    'сироватка корейська',
  ],
  authors: [{ name: 'eonni' }],
  creator: 'eonni',
  publisher: 'eonni',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  // Favicon strategy:
  //   • /logo-icon.svg — square (1:1) version of the wordmark for tabs/PWA.
  //     Google's SERP favicon crawler REQUIRES a square icon — the original
  //     /logo.svg is 139×56 (rectangular) so Google rejects it and falls back
  //     to the generic globe. Square wrapper fixes that.
  //   • /icon-96.png, /icon-192.png, /favicon.ico — raster fallbacks at the
  //     "multiple of 48" sizes Google specifically looks for.
  icons: {
    icon: [
      { url: '/logo-icon.svg', type: 'image/svg+xml' },
      { url: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icon-96.png', sizes: '96x96', type: 'image/png' },
      { url: '/favicon.ico', sizes: '48x48', type: 'image/png' },
    ],
    apple: '/icon-192.png',
    shortcut: '/favicon.ico',
  },
  alternates: {
    canonical: '/',
  },
  openGraph: {
    type: 'website',
    locale: 'uk_UA',
    url: SITE_URL,
    siteName: 'eonni',
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    // OG image is auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    // Twitter image is auto-generated by src/app/opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
    other: process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION
      ? { 'msvalidate.01': process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION }
      : undefined,
  },
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: '#E2F9FF',
}

const organizationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'OnlineStore',
  '@id': `${SITE_URL}/#organization`,
  name: 'eonni',
  alternateName: 'Eonni',
  legalName: 'ФОП Людвічук Катерина Миколаївна',
  taxID: '3402113126',
  url: SITE_URL,
  logo: `${SITE_URL}/icon-192.png`,
  image: `${SITE_URL}/icon-192.png`,
  description: SITE_DESCRIPTION,
  priceRange: '₴',
  currenciesAccepted: 'UAH',
  paymentAccepted: 'Cash, Credit Card, Apple Pay, Google Pay',
  areaServed: { '@type': 'Country', name: 'Ukraine' },
  address: {
    '@type': 'PostalAddress',
    streetAddress: "вул. Левка Лук'яненка, 21",
    addressLocality: 'Київ',
    addressRegion: 'Київська область',
    postalCode: '04207',
    addressCountry: 'UA',
  },
  telephone: '+380732737330',
  email: 'eonnisupport@gmail.com',
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'customer service',
    telephone: '+380732737330',
    email: 'eonnisupport@gmail.com',
    availableLanguage: ['uk', 'ru'],
  },
  hasMerchantReturnPolicy: {
    '@type': 'MerchantReturnPolicy',
    merchantReturnLink: `${SITE_URL}/returns-exchange`,
  },
  hasShippingService: {
    '@type': 'ShippingService',
    name: 'Доставка Новою Поштою по Україні',
    description:
      'Доставка у відділення або поштомат Нової Пошти за тарифами перевізника. Безкоштовно для замовлень від 1500 ₴.',
    fulfillmentType: 'https://schema.org/FulfillmentTypeCollectionPoint',
    handlingTime: {
      '@type': 'ServicePeriod',
      duration: {
        '@type': 'QuantitativeValue',
        minValue: 0,
        maxValue: 1,
        unitCode: 'DAY',
      },
    },
    shippingConditions: [
      {
        '@type': 'ShippingConditions',
        orderValue: {
          '@type': 'MonetaryAmount',
          maxValue: 1499.99,
          currency: 'UAH',
        },
        shippingDestination: {
          '@type': 'DefinedRegion',
          addressCountry: 'UA',
        },
        transitTime: {
          '@type': 'ServicePeriod',
          duration: {
            '@type': 'QuantitativeValue',
            minValue: 1,
            maxValue: 3,
            unitCode: 'DAY',
          },
        },
      },
      {
        '@type': 'ShippingConditions',
        orderValue: {
          '@type': 'MonetaryAmount',
          minValue: 1500,
          currency: 'UAH',
        },
        shippingDestination: {
          '@type': 'DefinedRegion',
          addressCountry: 'UA',
        },
        shippingRate: {
          '@type': 'MonetaryAmount',
          value: 0,
          currency: 'UAH',
        },
        transitTime: {
          '@type': 'ServicePeriod',
          duration: {
            '@type': 'QuantitativeValue',
            minValue: 1,
            maxValue: 3,
            unitCode: 'DAY',
          },
        },
      },
    ],
  },
  sameAs: [
    'https://www.instagram.com/eonni.korean.cosmetics',
    'https://t.me/Eonni_KC',
  ],
}

const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'eonni',
  alternateName: 'Eonni',
  url: SITE_URL,
  potentialAction: {
    '@type': 'SearchAction',
    target: `${SITE_URL}/catalog?search={search_term_string}`,
    'query-input': 'required name=search_term_string',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="uk">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
      </head>
      <body className="antialiased">
        <MicrosoftClarity />
        <CartProvider>
          <WishlistProvider>
            <LenisProvider />
            <Header />
            <div className="h-[86px]" />
            {children}
            <SupportFAB />
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  )
}
